# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: DARKYOLKS
logo: '/assets/images/yolkPNG.png'
email: grant@darkyolks.com
description: Thoughts, write ups, and weird little oddities.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://darkyolks.com" # the base hostname & protocol for your site, e.g. http://example.com
# social:
#  github: darkyolks
#  linkedin: grant-wilsey
#  twitter: dark_yolks

# Theme Settings
author:
  name: Grant Wilsey
  avatar: /assets/images/darkyolks-favi.jpg

# Hero Settings
hero:
  title: DARK YOLKS
  description: Thoughts, write ups, and weird little oddities.
  image: '/assets/images/hero.jpg' # background image for home page (hero)
  url: "https://darkyolks.com"


#-------------------------------
# Contact Settings
contact:
  email: grant@darkyolks.com # Add your email for contact form
  description: # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/dark_yolks"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCzQ2vDjfscqSpXvSHhejJMg"}
- {icon: "ion-logo-github", link: "https://github.com/darkyolks"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/sebastianschuetze"}


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

# Navigation
#navigation:
#  - title: Home
#    url: /
#  - title: Write Ups
#    url: /write-ups/
#  - title: Labs
#    url: /labs/
#  - title: Certifications
#    url: /certifications
#  - title: About Me
#    url: /about/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
