markdown: kramdown
# plugins:
#   - jekyll-paginate
#   - jekyll-seo-tag
paginate: 6
paginate_path: "/page/:num/"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Write Ups
    url: /write-ups
  - title: Labs
    url: /labs
  - title: About Me
    url: /about

sass:
  load_paths:
    - _sass
    - yolks-theme/_sass
  style: compressed